[server]
host = "0.0.0.0"
port = 8216

[server.mtls]
tls_enabled = true
verify_client = true
cert_file = "certs/<AIC>.pem"
key_file = "certs/<AIC>.key"
ca_file = "certs/trust-bundle.pem"

[concurrency]
max_concurrent_tasks = 10

[log]
level = "INFO"
