CA_SERVER_BASE_URL = https://ioa.pub/ca-server/acps-atr-v2
CHALLENGE_SERVER_BASE_URL = http://8.146.235.243:8004/acps-atr-v2
ACCOUNT_KEY_PATH = /root/WORK/ACPs-app/private/account.key
CERTS_DIR = /root/WORK/ACPs-app/certs
PRIVATE_KEYS_DIR = /root/WORK/ACPs-app/private
CSR_DIR = /root/WORK/ACPs-app/csr
TRUST_BUNDLE_PATH = /root/WORK/ACPs-app/certs/trust-bundle.pem
